### ISSUE TITLE
Voices attached to corpses permanently

### ISSUE THREAD

**Issue by xsigsig** [ege-adam/MoreScreams#1] opened 2023-11-30 06:17 UTC
When a player dies, I'm able to hear them permanently after their death despite setting my config to only last 1 second after death. This also causes me to be unable to hear other dead players when I'm dead since the voices are still being emitted from their corpse. I am using are More Company.

**Comment by KlutzyBubbles** [comment] 2023-11-30 11:32
Also happens in biggerlobby

**Comment by ege-adam** [comment] 2023-12-02 02:53
It must be fixed with latest pre-release . But I haven't had a chance to test it completely yet.

**Comment by ege-adam** [comment] 2023-12-02 13:07
I was able to reproduce the bug and found the cause. Now it is fixed properly. I tried to break it intentionally but it was working perfectly fine. Feel free to re-open the issue if it is not fixed with the latest release.

**Closed as completed by ege-adam** 2023-12-02 13:07 UTC
Labels: bug
